CREATE TABLE IF NOT EXISTS workflow_run (
    run_id VARCHAR(64) NOT NULL COMMENT '工作流运行ID',
    trace_id VARCHAR(64) NOT NULL COMMENT '链路追踪ID',
    workflow_name VARCHAR(128) NOT NULL COMMENT '工作流名称',
    biz_type VARCHAR(64) NOT NULL COMMENT '业务类型',
    biz_id VARCHAR(128) NOT NULL COMMENT '业务ID',
    status VARCHAR(32) NOT NULL COMMENT '运行状态',
    start_time DATETIME NULL COMMENT '开始时间',
    end_time DATETIME NULL COMMENT '结束时间',
    duration_ms BIGINT NULL COMMENT '耗时毫秒',
    input_summary TEXT NULL COMMENT '输入摘要',
    output_summary TEXT NULL COMMENT '输出摘要',
    failure_node VARCHAR(128) NULL COMMENT '失败节点',
    failure_reason VARCHAR(512) NULL COMMENT '失败原因',
    failure_detail TEXT NULL COMMENT '失败详情',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记：0未删除，1已删除',
    delete_time DATETIME NULL COMMENT '删除时间',
    version INT NOT NULL DEFAULT 0 COMMENT '版本号',
    PRIMARY KEY (run_id),
    KEY idx_workflow_run_trace_id (trace_id),
    KEY idx_workflow_run_biz (biz_type, biz_id),
    KEY idx_workflow_run_create_time (create_time)
) COMMENT='工作流运行记录';

CREATE TABLE IF NOT EXISTS workflow_node_run (
    node_run_id VARCHAR(64) NOT NULL COMMENT '节点运行ID',
    run_id VARCHAR(64) NOT NULL COMMENT '工作流运行ID',
    trace_id VARCHAR(64) NOT NULL COMMENT '链路追踪ID',
    node_name VARCHAR(128) NOT NULL COMMENT '节点名称',
    status VARCHAR(32) NOT NULL COMMENT '运行状态',
    start_time DATETIME NULL COMMENT '开始时间',
    end_time DATETIME NULL COMMENT '结束时间',
    duration_ms BIGINT NULL COMMENT '耗时毫秒',
    input_summary TEXT NULL COMMENT '输入摘要',
    output_summary TEXT NULL COMMENT '输出摘要',
    failure_reason VARCHAR(512) NULL COMMENT '失败原因',
    failure_detail TEXT NULL COMMENT '失败详情',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记：0未删除，1已删除',
    delete_time DATETIME NULL COMMENT '删除时间',
    version INT NOT NULL DEFAULT 0 COMMENT '版本号',
    PRIMARY KEY (node_run_id),
    KEY idx_workflow_node_run_run_id (run_id),
    KEY idx_workflow_node_run_trace_id (trace_id)
) COMMENT='工作流节点运行记录';

CREATE TABLE IF NOT EXISTS model_call_log (
    call_id VARCHAR(64) NOT NULL COMMENT '模型调用ID',
    trace_id VARCHAR(64) NOT NULL COMMENT '链路追踪ID',
    biz_type VARCHAR(64) NOT NULL COMMENT '业务类型',
    biz_id VARCHAR(128) NULL COMMENT '业务ID',
    model_profile VARCHAR(128) NOT NULL COMMENT '模型配置名称',
    provider VARCHAR(64) NOT NULL COMMENT '模型厂商',
    base_url VARCHAR(512) NOT NULL COMMENT '模型服务地址',
    model_name VARCHAR(128) NOT NULL COMMENT '模型名称',
    request_type VARCHAR(64) NOT NULL COMMENT '请求类型',
    status VARCHAR(32) NOT NULL COMMENT '调用状态',
    prompt_tokens INT NULL COMMENT '提示词Token数',
    completion_tokens INT NULL COMMENT '输出Token数',
    total_tokens INT NULL COMMENT '总Token数',
    token_usage_source VARCHAR(32) NULL COMMENT 'Token用量统计来源',
    duration_ms BIGINT NULL COMMENT '耗时毫秒',
    first_token_latency_ms BIGINT NULL COMMENT '首个Token或首个分片耗时，单位毫秒',
    chunk_count INT NULL COMMENT '流式响应分片数量',
    output_char_count INT NULL COMMENT '输出字符数',
    estimated_output_tokens INT NULL COMMENT '估算输出Token数量',
    attempt_no INT NOT NULL DEFAULT 1 COMMENT '第几次尝试',
    fallback_from_call_id VARCHAR(64) NULL COMMENT '降级来源调用ID',
    fallback_reason VARCHAR(128) NULL COMMENT '降级原因',
    fallback_from VARCHAR(128) NULL COMMENT '降级来源模型',
    fallback_to VARCHAR(128) NULL COMMENT '降级目标模型',
    error_code VARCHAR(128) NULL COMMENT '错误码',
    error_message VARCHAR(512) NULL COMMENT '错误信息',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    PRIMARY KEY (call_id),
    KEY idx_model_call_log_trace_id (trace_id),
    KEY idx_model_call_log_biz (biz_type, biz_id),
    KEY idx_model_call_log_create_time (create_time)
) COMMENT='模型调用日志';

CREATE TABLE IF NOT EXISTS document (
    document_id BIGINT NOT NULL COMMENT '文档ID',
    title VARCHAR(256) NOT NULL COMMENT '文档标题',
    description VARCHAR(1024) NULL COMMENT '文档描述',
    original_file_name VARCHAR(512) NOT NULL COMMENT '原始文件名',
    file_type VARCHAR(32) NOT NULL COMMENT '文件类型',
    file_size BIGINT NULL COMMENT '文件大小',
    original_file_url VARCHAR(1024) NULL COMMENT '原始文件地址',
    original_object_name VARCHAR(1024) NULL COMMENT '原始文件对象名',
    parsed_file_url VARCHAR(1024) NULL COMMENT '解析后文件地址',
    parsed_object_name VARCHAR(1024) NULL COMMENT '解析后文件对象名',
    parsed_content_type VARCHAR(128) NULL COMMENT '解析后内容类型',
    status VARCHAR(32) NOT NULL COMMENT '文档状态',
    process_id VARCHAR(64) NULL COMMENT '当前文档处理轮次ID',
    message_status VARCHAR(32) NULL COMMENT '当前处理轮次消息状态',
    consumed_times INT NOT NULL DEFAULT 0 COMMENT '当前处理轮次已消费次数',
    last_message_id VARCHAR(128) NULL COMMENT '最近一次消费的RocketMQ消息ID',
    queue_stage VARCHAR(32) NULL COMMENT '排队阶段',
    queue_time DATETIME NULL COMMENT '排队时间',
    process_start_time DATETIME NULL COMMENT '处理开始时间',
    process_end_time DATETIME NULL COMMENT '处理结束时间',
    process_config_json TEXT NULL COMMENT '处理配置快照',
    failure_stage VARCHAR(64) NULL COMMENT '失败阶段',
    failure_reason VARCHAR(512) NULL COMMENT '失败原因',
    failure_detail TEXT NULL COMMENT '失败详情',
    retry_count INT NOT NULL DEFAULT 0 COMMENT '已重试次数',
    max_retry_count INT NOT NULL DEFAULT 3 COMMENT '最大重试次数',
    last_retry_time DATETIME NULL COMMENT '最近重试时间',
    cleanup_status VARCHAR(32) NULL COMMENT '清理状态',
    cleanup_retry_count INT NOT NULL DEFAULT 0 COMMENT '清理重试次数',
    cleanup_failure_reason VARCHAR(512) NULL COMMENT '清理失败原因',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记：0未删除，1已删除',
    delete_time DATETIME NULL COMMENT '删除时间',
    version INT NOT NULL DEFAULT 0 COMMENT '版本号',
    PRIMARY KEY (document_id),
    KEY idx_document_status (status),
    KEY idx_document_create_time (create_time),
    KEY idx_document_del_flag (del_flag)
) COMMENT='文档表';

CREATE TABLE IF NOT EXISTS document_pipeline_outbox (
    outbox_id BIGINT NOT NULL COMMENT 'Outbox记录ID',
    document_id BIGINT NOT NULL COMMENT '文档ID',
    process_id VARCHAR(64) NOT NULL COMMENT '文档处理流水号',
    message_key VARCHAR(128) NOT NULL COMMENT '消息唯一键',
    topic VARCHAR(128) NOT NULL COMMENT '消息主题',
    message_body TEXT NOT NULL COMMENT '消息内容',
    publish_status VARCHAR(32) NOT NULL COMMENT '发布状态',
    publish_retry_count INT NOT NULL DEFAULT 0 COMMENT '发布重试次数',
    next_retry_time DATETIME NULL COMMENT '下次重试时间',
    lock_owner VARCHAR(128) NULL COMMENT '锁持有者',
    lock_time DATETIME NULL COMMENT '加锁时间',
    published_time DATETIME NULL COMMENT '发布时间',
    failure_reason VARCHAR(1024) NULL COMMENT '失败原因',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    -- 主键：Outbox记录ID
    PRIMARY KEY (outbox_id),
    -- 唯一索引：保证消息唯一键不重复
    UNIQUE KEY uk_document_pipeline_outbox_message_key (message_key),
    -- 任务索引：按发布状态和下次重试时间扫描待发布任务
    KEY idx_document_pipeline_outbox_publish_task (publish_status, next_retry_time)
) COMMENT='文档流水线消息Outbox表';

CREATE TABLE IF NOT EXISTS document_chunk (
    chunk_id VARCHAR(64) NOT NULL COMMENT '片段ID',
    document_id BIGINT NOT NULL COMMENT '文档ID',
    chunk_order INT NOT NULL COMMENT '片段顺序',
    parent_chunk_id VARCHAR(64) NULL COMMENT '父片段ID',
    section_id BIGINT NULL COMMENT '所属章节ID',
    text MEDIUMTEXT NOT NULL COMMENT '片段文本',
    index_content MEDIUMTEXT NULL COMMENT '用于索引的片段内容',
    metadata_json TEXT NULL COMMENT '元数据JSON',
    token_count INT NULL COMMENT 'Token数量',
    status VARCHAR(32) NOT NULL COMMENT '片段状态',
    skip_index TINYINT NOT NULL DEFAULT 0 COMMENT '是否跳过索引：0否，1是',
    vector_id VARCHAR(128) NULL COMMENT '向量索引ID',
    keyword_index_id VARCHAR(128) NULL COMMENT '关键词索引ID',
    failure_reason VARCHAR(512) NULL COMMENT '失败原因',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记：0未删除，1已删除',
    delete_time DATETIME NULL COMMENT '删除时间',
    version INT NOT NULL DEFAULT 0 COMMENT '版本号',
    PRIMARY KEY (chunk_id),
    KEY idx_document_chunk_document_id (document_id),
    KEY idx_document_chunk_status (status),
    KEY idx_document_chunk_order (document_id, chunk_order),
    KEY idx_document_chunk_section (document_id, section_id)
) COMMENT='文档片段表';

CREATE TABLE IF NOT EXISTS document_section (
    section_id BIGINT NOT NULL COMMENT '章节ID',
    document_id BIGINT NOT NULL COMMENT '文档ID',
    parent_section_id BIGINT NULL COMMENT '父章节ID',
    title VARCHAR(512) NOT NULL COMMENT '章节标题',
    heading_path_json TEXT NOT NULL COMMENT '标题层级路径JSON',
    heading_level INT NOT NULL COMMENT '标题层级',
    start_line INT NOT NULL COMMENT '章节起始行号',
    end_line INT NOT NULL COMMENT '章节结束行号',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记：0未删除，1已删除',
    PRIMARY KEY (section_id),
    KEY idx_document_section_document (document_id),
    KEY idx_document_section_parent (document_id, parent_section_id)
) COMMENT='文档章节结构表';

CREATE TABLE IF NOT EXISTS model_config (
    config_id BIGINT NOT NULL COMMENT '模型配置ID',
    config_key VARCHAR(128) NOT NULL COMMENT '模型配置唯一key',
    model_type VARCHAR(32) NOT NULL COMMENT '模型类型',
    provider VARCHAR(64) NOT NULL COMMENT '模型厂商',
    base_url VARCHAR(512) NOT NULL COMMENT '模型服务地址',
    endpoint_path VARCHAR(256) NULL COMMENT '模型接口路径',
    api_key_cipher VARCHAR(1024) NULL COMMENT '加密后的API Key',
    api_key_mask VARCHAR(128) NULL COMMENT 'API Key脱敏值',
    model_name VARCHAR(128) NOT NULL COMMENT '模型名称',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    timeout_ms INT NOT NULL DEFAULT 30000 COMMENT '超时时间毫秒',
    max_retries INT NOT NULL DEFAULT 0 COMMENT '最大重试次数',
    version BIGINT NOT NULL DEFAULT 1 COMMENT '单条配置版本',
    extra_config TEXT NULL COMMENT '扩展配置JSON',
    remark VARCHAR(512) NULL COMMENT '备注',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记：0未删除，1已删除',
    delete_time DATETIME NULL COMMENT '删除时间',
    PRIMARY KEY (config_id),
    UNIQUE KEY uk_model_config_key (config_key),
    KEY idx_model_config_type_provider (model_type, provider),
    KEY idx_model_config_del_flag (del_flag)
) COMMENT='模型配置表';

CREATE TABLE IF NOT EXISTS model_route (
    route_id BIGINT NOT NULL COMMENT '模型路由ID',
    route_key VARCHAR(128) NOT NULL COMMENT '模型路由唯一key',
    model_type VARCHAR(32) NOT NULL COMMENT '模型类型',
    strategy VARCHAR(32) NOT NULL COMMENT '路由策略',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    remark VARCHAR(512) NULL COMMENT '备注',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记：0未删除，1已删除',
    delete_time DATETIME NULL COMMENT '删除时间',
    version INT NOT NULL DEFAULT 0 COMMENT '版本号',
    PRIMARY KEY (route_id),
    UNIQUE KEY uk_model_route_key (route_key),
    KEY idx_model_route_type (model_type),
    KEY idx_model_route_del_flag (del_flag)
) COMMENT='模型路由表';

CREATE TABLE IF NOT EXISTS model_route_config (
    route_config_id BIGINT NOT NULL COMMENT '模型路由配置关联ID',
    route_id BIGINT NOT NULL COMMENT '模型路由ID',
    config_id BIGINT NOT NULL COMMENT '模型配置ID',
    role VARCHAR(32) NOT NULL COMMENT '路由下模型配置角色',
    priority INT NOT NULL DEFAULT 0 COMMENT '优先级',
    weight INT NOT NULL DEFAULT 0 COMMENT '权重',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记：0未删除，1已删除',
    delete_time DATETIME NULL COMMENT '删除时间',
    version INT NOT NULL DEFAULT 0 COMMENT '版本号',
    PRIMARY KEY (route_config_id),
    UNIQUE KEY uk_model_route_config (route_id, config_id, role),
    KEY idx_model_route_config_route_id (route_id),
    KEY idx_model_route_config_config_id (config_id),
    KEY idx_model_route_config_del_flag (del_flag)
) COMMENT='模型路由配置关联表';

CREATE TABLE IF NOT EXISTS model_registry_version (
    version_id BIGINT NOT NULL COMMENT '版本记录ID',
    version_no BIGINT NOT NULL COMMENT '全局版本号',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    PRIMARY KEY (version_id)
) COMMENT='模型注册表版本表';

CREATE TABLE IF NOT EXISTS model_governance_config (
    governance_id BIGINT NOT NULL COMMENT '模型治理配置ID',
    binding_mode VARCHAR(32) NOT NULL DEFAULT 'CONFIG' COMMENT '治理配置绑定模式：CONFIG按模型配置绑定，ROUTE按路由key绑定',
    config_id BIGINT NULL COMMENT '模型配置ID',
    route_key VARCHAR(128) NULL COMMENT '模型路由key，ROUTE绑定模式使用',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用治理配置',
    retry_enabled TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否启用重试',
    max_attempts INT NOT NULL DEFAULT 1 COMMENT '最大尝试次数',
    retry_wait_ms INT NOT NULL DEFAULT 200 COMMENT '重试等待时间毫秒',
    circuit_enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用熔断',
    failure_rate_threshold INT NOT NULL DEFAULT 50 COMMENT '失败率阈值',
    slow_call_rate_threshold INT NOT NULL DEFAULT 50 COMMENT '慢调用比例阈值',
    slow_call_duration_ms INT NOT NULL DEFAULT 30000 COMMENT '慢调用判定时长毫秒',
    minimum_number_of_calls INT NOT NULL DEFAULT 10 COMMENT '熔断统计最小调用数',
    sliding_window_size INT NOT NULL DEFAULT 20 COMMENT '熔断滑动窗口大小',
    wait_duration_in_open_state_ms INT NOT NULL DEFAULT 30000 COMMENT '熔断打开后等待时间毫秒',
    rate_limit_enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用限流',
    limit_for_period INT NOT NULL DEFAULT 60 COMMENT '单周期允许调用数',
    limit_refresh_period_ms INT NOT NULL DEFAULT 60000 COMMENT '限流周期刷新时间毫秒',
    timeout_duration_ms INT NOT NULL DEFAULT 0 COMMENT '获取限流许可等待时间毫秒',
    bulkhead_enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用并发隔离',
    time_limiter_enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用同步调用超时保护',
    time_limiter_timeout_ms INT NOT NULL DEFAULT 60000 COMMENT '同步调用超时时间，单位毫秒',
    stream_first_chunk_timeout_ms INT NOT NULL DEFAULT 30000 COMMENT '流式调用首个分片超时时间，单位毫秒',
    stream_max_duration_ms INT NOT NULL DEFAULT 300000 COMMENT '流式调用最大持续时间，单位毫秒',
    max_concurrent_calls INT NOT NULL DEFAULT 8 COMMENT '最大并发调用数',
    max_wait_duration_ms INT NOT NULL DEFAULT 0 COMMENT '获取并发许可等待时间毫秒',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记：0未删除，1已删除',
    delete_time DATETIME NULL COMMENT '删除时间',
    PRIMARY KEY (governance_id),
    KEY idx_model_governance_config_config (binding_mode, config_id, del_flag),
    KEY idx_model_governance_config_route (binding_mode, route_key, del_flag),
    KEY idx_model_governance_del_flag (del_flag)
) COMMENT='模型治理配置表';

INSERT INTO model_registry_version (version_id, version_no, update_time)
SELECT 1, 1, NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM model_registry_version WHERE version_id = 1
);

CREATE TABLE IF NOT EXISTS chat_conversation (
    conversation_id VARCHAR(64) NOT NULL COMMENT '会话ID',
    user_id VARCHAR(64) NOT NULL COMMENT '用户ID',
    title VARCHAR(256) NOT NULL COMMENT '会话标题',
    status VARCHAR(32) NOT NULL COMMENT '会话状态',
    last_message_id VARCHAR(64) NULL COMMENT '最近一条消息ID',
    last_message_time DATETIME NULL COMMENT '最近一条消息时间',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记：0未删除，1已删除',
    PRIMARY KEY (conversation_id),
    KEY idx_chat_conversation_user_status_time (user_id, status, update_time),
    KEY idx_chat_conversation_user_id (user_id)
) COMMENT='聊天会话';

CREATE TABLE IF NOT EXISTS chat_message (
    message_id VARCHAR(64) NOT NULL COMMENT '消息ID',
    conversation_id VARCHAR(64) NOT NULL COMMENT '会话ID',
    user_id VARCHAR(64) NOT NULL COMMENT '用户ID',
    sequence BIGINT NOT NULL COMMENT '会话内消息序号',
    role VARCHAR(32) NOT NULL COMMENT '消息角色',
    status VARCHAR(32) NOT NULL COMMENT '消息状态',
    content MEDIUMTEXT NULL COMMENT '消息正文',
    thinking_content MEDIUMTEXT NULL COMMENT '思考内容',
    references_json TEXT NULL COMMENT '引用信息JSON',
    prompt_tokens INT NULL COMMENT '输入Token数',
    completion_tokens INT NULL COMMENT '输出Token数',
    total_tokens INT NULL COMMENT '总Token数',
    failure_code VARCHAR(128) NULL COMMENT '失败编码',
    failure_message VARCHAR(512) NULL COMMENT '失败信息',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记：0未删除，1已删除',
    PRIMARY KEY (message_id),
    UNIQUE KEY uk_chat_message_conversation_sequence (conversation_id, sequence),
    KEY idx_chat_message_conversation_sequence (conversation_id, sequence),
    KEY idx_chat_message_conversation_status_sequence (conversation_id, status, sequence),
    KEY idx_chat_message_user_conversation_sequence (user_id, conversation_id, sequence)
) COMMENT='聊天消息';

CREATE TABLE IF NOT EXISTS chat_conversation_summary (
    summary_id VARCHAR(64) NOT NULL COMMENT '摘要ID',
    conversation_id VARCHAR(64) NOT NULL COMMENT '会话ID',
    user_id VARCHAR(64) NOT NULL COMMENT '用户ID',
    content TEXT NOT NULL COMMENT '摘要内容',
    last_message_id VARCHAR(64) NOT NULL COMMENT '摘要覆盖的最后消息ID',
    summary_version BIGINT NOT NULL COMMENT '摘要版本',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记：0未删除，1已删除',
    PRIMARY KEY (summary_id),
    UNIQUE KEY uk_chat_summary_conversation_version (conversation_id, summary_version),
    KEY idx_chat_summary_conversation_version (conversation_id, summary_version),
    KEY idx_chat_summary_user_conversation_version (user_id, conversation_id, summary_version)
) COMMENT='聊天会话摘要';

CREATE TABLE prompt_definition (
    prompt_id BIGINT NOT NULL COMMENT '提示词定义ID',
    prompt_code VARCHAR(128) NOT NULL COMMENT '提示词唯一编码',
    name VARCHAR(128) NOT NULL COMMENT '提示词名称',
    variable_schema JSON NOT NULL COMMENT '变量契约JSON',
    enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
    current_release_id BIGINT NULL COMMENT '当前发布记录ID',
    current_release_revision BIGINT NOT NULL DEFAULT 0 COMMENT '当前发布代次',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    PRIMARY KEY (prompt_id),
    UNIQUE KEY uk_prompt_definition_code (prompt_code)
) COMMENT='提示词定义表';

CREATE TABLE prompt_version (
    version_id BIGINT NOT NULL COMMENT '提示词版本ID',
    prompt_id BIGINT NOT NULL COMMENT '提示词定义ID',
    version_no BIGINT NOT NULL COMMENT '定义内版本号',
    content MEDIUMTEXT NOT NULL COMMENT '模板正文',
    content_checksum CHAR(64) NOT NULL COMMENT '正文SHA-256摘要',
    variable_schema_snapshot JSON NOT NULL COMMENT '变量契约快照',
    created_by VARCHAR(64) NOT NULL COMMENT '创建人',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    remark VARCHAR(512) NULL COMMENT '变更说明',
    PRIMARY KEY (version_id),
    UNIQUE KEY uk_prompt_version_prompt_no (prompt_id, version_no),
    KEY idx_prompt_version_prompt (prompt_id)
) COMMENT='提示词不可变版本表';

CREATE TABLE prompt_release (
    release_id BIGINT NOT NULL COMMENT '提示词发布记录ID',
    prompt_id BIGINT NOT NULL COMMENT '提示词定义ID',
    stable_version_id BIGINT NOT NULL COMMENT '正式版本ID',
    canary_version_id BIGINT NULL COMMENT '灰度版本ID',
    canary_rule JSON NULL COMMENT '灰度规则JSON',
    release_revision BIGINT NOT NULL COMMENT '发布代次',
    released_by VARCHAR(64) NOT NULL COMMENT '发布人',
    released_at DATETIME NOT NULL COMMENT '发布时间',
    rollback_from_release_id BIGINT NULL COMMENT '回滚来源发布记录ID',
    remark VARCHAR(512) NULL COMMENT '发布说明',
    PRIMARY KEY (release_id),
    UNIQUE KEY uk_prompt_release_prompt_revision (prompt_id, release_revision),
    KEY idx_prompt_release_prompt_time (prompt_id, released_at)
) COMMENT='提示词发布记录表';
