CREATE TABLE IF NOT EXISTS workflow_run (
    run_id VARCHAR(64) NOT NULL COMMENT '工作流运行ID',
    trace_id VARCHAR(64) NOT NULL COMMENT '链路追踪ID',
    workflow_name VARCHAR(128) NOT NULL COMMENT '工作流名称',
    biz_type VARCHAR(64) NOT NULL COMMENT '业务类型',
    biz_id VARCHAR(128) NOT NULL COMMENT '业务ID',
    status VARCHAR(32) NOT NULL COMMENT '运行状态',
    start_time DATETIME NULL COMMENT '开始时间',
    end_time DATETIME NULL COMMENT '结束时间',
    duration_ms BIGINT NULL COMMENT '耗时毫秒',
    input_summary TEXT NULL COMMENT '输入摘要',
    output_summary TEXT NULL COMMENT '输出摘要',
    failure_node VARCHAR(128) NULL COMMENT '失败节点',
    failure_reason VARCHAR(512) NULL COMMENT '失败原因',
    failure_detail TEXT NULL COMMENT '失败详情',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记：0未删除，1已删除',
    delete_time DATETIME NULL COMMENT '删除时间',
    version INT NOT NULL DEFAULT 0 COMMENT '版本号',
    PRIMARY KEY (run_id),
    KEY idx_workflow_run_trace_id (trace_id),
    KEY idx_workflow_run_biz (biz_type, biz_id),
    KEY idx_workflow_run_create_time (create_time)
) COMMENT='工作流运行记录';

CREATE TABLE IF NOT EXISTS workflow_node_run (
    node_run_id VARCHAR(64) NOT NULL COMMENT '节点运行ID',
    run_id VARCHAR(64) NOT NULL COMMENT '工作流运行ID',
    trace_id VARCHAR(64) NOT NULL COMMENT '链路追踪ID',
    node_name VARCHAR(128) NOT NULL COMMENT '节点名称',
    status VARCHAR(32) NOT NULL COMMENT '运行状态',
    start_time DATETIME NULL COMMENT '开始时间',
    end_time DATETIME NULL COMMENT '结束时间',
    duration_ms BIGINT NULL COMMENT '耗时毫秒',
    input_summary TEXT NULL COMMENT '输入摘要',
    output_summary TEXT NULL COMMENT '输出摘要',
    failure_reason VARCHAR(512) NULL COMMENT '失败原因',
    failure_detail TEXT NULL COMMENT '失败详情',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记：0未删除，1已删除',
    delete_time DATETIME NULL COMMENT '删除时间',
    version INT NOT NULL DEFAULT 0 COMMENT '版本号',
    PRIMARY KEY (node_run_id),
    KEY idx_workflow_node_run_run_id (run_id),
    KEY idx_workflow_node_run_trace_id (trace_id)
) COMMENT='工作流节点运行记录';

CREATE TABLE IF NOT EXISTS model_call_log (
    call_id VARCHAR(64) NOT NULL COMMENT '模型调用ID',
    trace_id VARCHAR(64) NOT NULL COMMENT '链路追踪ID',
    biz_type VARCHAR(64) NOT NULL COMMENT '业务类型',
    biz_id VARCHAR(128) NULL COMMENT '业务ID',
    model_profile VARCHAR(128) NOT NULL COMMENT '模型配置名称',
    provider VARCHAR(64) NOT NULL COMMENT '模型厂商',
    base_url VARCHAR(512) NOT NULL COMMENT '模型服务地址',
    model_name VARCHAR(128) NOT NULL COMMENT '模型名称',
    request_type VARCHAR(64) NOT NULL COMMENT '请求类型',
    status VARCHAR(32) NOT NULL COMMENT '调用状态',
    prompt_tokens INT NULL COMMENT '提示词Token数',
    completion_tokens INT NULL COMMENT '输出Token数',
    total_tokens INT NULL COMMENT '总Token数',
    duration_ms BIGINT NULL COMMENT '耗时毫秒',
    fallback_from VARCHAR(128) NULL COMMENT '降级来源模型',
    fallback_to VARCHAR(128) NULL COMMENT '降级目标模型',
    error_code VARCHAR(128) NULL COMMENT '错误码',
    error_message VARCHAR(512) NULL COMMENT '错误信息',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    PRIMARY KEY (call_id),
    KEY idx_model_call_log_trace_id (trace_id),
    KEY idx_model_call_log_biz (biz_type, biz_id),
    KEY idx_model_call_log_create_time (create_time)
) COMMENT='模型调用日志';
