CREATE TABLE IF NOT EXISTS document (
    document_id BIGINT NOT NULL COMMENT '文档ID',
    title VARCHAR(256) NOT NULL COMMENT '文档标题',
    description VARCHAR(1024) NULL COMMENT '文档描述',
    original_file_name VARCHAR(512) NOT NULL COMMENT '原始文件名',
    file_type VARCHAR(32) NOT NULL COMMENT '文件类型',
    file_size BIGINT NULL COMMENT '文件大小',
    original_file_url VARCHAR(1024) NULL COMMENT '原始文件地址',
    parsed_file_url VARCHAR(1024) NULL COMMENT '解析后文件地址',
    status VARCHAR(32) NOT NULL COMMENT '文档状态',
    queue_stage VARCHAR(32) NULL COMMENT '排队阶段',
    queue_time DATETIME NULL COMMENT '排队时间',
    process_start_time DATETIME NULL COMMENT '处理开始时间',
    process_end_time DATETIME NULL COMMENT '处理结束时间',
    process_config_json TEXT NULL COMMENT '处理配置快照',
    failure_stage VARCHAR(64) NULL COMMENT '失败阶段',
    failure_reason VARCHAR(512) NULL COMMENT '失败原因',
    failure_detail TEXT NULL COMMENT '失败详情',
    retry_count INT NOT NULL DEFAULT 0 COMMENT '已重试次数',
    max_retry_count INT NOT NULL DEFAULT 3 COMMENT '最大重试次数',
    last_retry_time DATETIME NULL COMMENT '最近重试时间',
    cleanup_status VARCHAR(32) NULL COMMENT '清理状态',
    cleanup_retry_count INT NOT NULL DEFAULT 0 COMMENT '清理重试次数',
    cleanup_failure_reason VARCHAR(512) NULL COMMENT '清理失败原因',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记：0未删除，1已删除',
    delete_time DATETIME NULL COMMENT '删除时间',
    version INT NOT NULL DEFAULT 0 COMMENT '版本号',
    PRIMARY KEY (document_id),
    KEY idx_document_status (status),
    KEY idx_document_create_time (create_time),
    KEY idx_document_del_flag (del_flag)
) COMMENT='文档表';

CREATE TABLE IF NOT EXISTS document_chunk (
    chunk_id VARCHAR(64) NOT NULL COMMENT '片段ID',
    document_id BIGINT NOT NULL COMMENT '文档ID',
    chunk_order INT NOT NULL COMMENT '片段顺序',
    parent_chunk_id VARCHAR(64) NULL COMMENT '父片段ID',
    text MEDIUMTEXT NOT NULL COMMENT '片段文本',
    metadata_json TEXT NULL COMMENT '元数据JSON',
    token_count INT NULL COMMENT 'Token数量',
    status VARCHAR(32) NOT NULL COMMENT '片段状态',
    skip_index TINYINT NOT NULL DEFAULT 0 COMMENT '是否跳过索引：0否，1是',
    vector_id VARCHAR(128) NULL COMMENT '向量索引ID',
    keyword_index_id VARCHAR(128) NULL COMMENT '关键词索引ID',
    failure_reason VARCHAR(512) NULL COMMENT '失败原因',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记：0未删除，1已删除',
    delete_time DATETIME NULL COMMENT '删除时间',
    version INT NOT NULL DEFAULT 0 COMMENT '版本号',
    PRIMARY KEY (chunk_id),
    KEY idx_document_chunk_document_id (document_id),
    KEY idx_document_chunk_status (status),
    KEY idx_document_chunk_order (document_id, chunk_order)
) COMMENT='文档片段表';
