CREATE TABLE IF NOT EXISTS model_governance_config (
    governance_id BIGINT NOT NULL COMMENT '模型治理配置ID',
    config_id BIGINT NOT NULL COMMENT '模型配置ID',
    enabled TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否启用治理配置',
    retry_enabled TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否启用重试',
    max_attempts INT NOT NULL DEFAULT 1 COMMENT '最大尝试次数',
    retry_wait_ms INT NOT NULL DEFAULT 0 COMMENT '重试等待时间毫秒',
    circuit_enabled TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否启用熔断',
    failure_rate_threshold INT NOT NULL DEFAULT 50 COMMENT '失败率阈值',
    slow_call_rate_threshold INT NOT NULL DEFAULT 100 COMMENT '慢调用比例阈值',
    slow_call_duration_ms INT NOT NULL DEFAULT 3000 COMMENT '慢调用判定时长毫秒',
    minimum_number_of_calls INT NOT NULL DEFAULT 10 COMMENT '熔断统计最小调用数',
    sliding_window_size INT NOT NULL DEFAULT 20 COMMENT '熔断滑动窗口大小',
    wait_duration_in_open_state_ms INT NOT NULL DEFAULT 30000 COMMENT '熔断打开后等待时间毫秒',
    rate_limit_enabled TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否启用限流',
    limit_for_period INT NOT NULL DEFAULT 100 COMMENT '单周期允许调用数',
    limit_refresh_period_ms INT NOT NULL DEFAULT 1000 COMMENT '限流周期刷新时间毫秒',
    timeout_duration_ms INT NOT NULL DEFAULT 0 COMMENT '获取限流许可等待时间毫秒',
    bulkhead_enabled TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否启用并发隔离',
    max_concurrent_calls INT NOT NULL DEFAULT 20 COMMENT '最大并发调用数',
    max_wait_duration_ms INT NOT NULL DEFAULT 0 COMMENT '获取并发许可等待时间毫秒',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记：0未删除，1已删除',
    delete_time DATETIME NULL COMMENT '删除时间',
    PRIMARY KEY (governance_id),
    UNIQUE KEY uk_model_governance_config_id (config_id),
    KEY idx_model_governance_del_flag (del_flag)
) COMMENT='模型治理配置表';
